import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react';
import FormInput from './FormInput';
const configs = {
  projects: { label: 'proyek', hint: 'Proyek pribadi, magang, organisasi, sukarela, atau penelitian. Jelaskan konteks dan peranmu dengan jujur.', fields: [['name', 'Nama proyek / kegiatan'], ['organization', 'Organisasi / konteks'], ['date', 'Periode (mis. Jan–Jun 2025)'], ['link', 'Tautan publik (opsional)'], ['description', 'Kontribusi dan hasil', true]] },
  certifications: { label: 'sertifikasi', hint: 'Masukkan sertifikasi atau pelatihan yang sudah kamu miliki. Cantumkan masa berlaku bila relevan.', fields: [['name', 'Nama sertifikasi / pelatihan'], ['issuer', 'Penerbit'], ['date', 'Tahun / masa berlaku'], ['link', 'Tautan kredensial (opsional)']] },
  languages: { label: 'bahasa', hint: 'Nyatakan tingkat kemampuan yang benar-benar bisa kamu gunakan. Hasil tes bersifat opsional.', fields: [['name', 'Bahasa'], ['level', 'Kemampuan (mis. percakapan / profesional)']] },
};
export default function AdditionalSection({ type, entries = [], setCVData }) {
  const config = configs[type];
  const mutate = fn => setCVData(prev => ({ ...prev, [type]: fn(prev[type] || []) }));
  const move = (index, offset) => mutate(items => { const copy = [...items]; [copy[index], copy[index + offset]] = [copy[index + offset], copy[index]]; return copy; });
  return <div className="entry-list"><p className="section-hint">{config.hint}</p>{entries.map((entry, index) => <div className="entry-card" key={entry.id}><div className="flex justify-between items-center gap-2"><h3>{entry.name || config.label} {index + 1}</h3><div className="flex gap-1"><button className="icon-button" aria-label={`Naikkan ${config.label} ${index + 1}`} disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp size={15} /></button><button className="icon-button" aria-label={`Turunkan ${config.label} ${index + 1}`} disabled={index === entries.length - 1} onClick={() => move(index, 1)}><ArrowDown size={15} /></button><button className="icon-button danger" aria-label={`Hapus ${config.label} ${index + 1}`} onClick={() => mutate(items => items.filter(item => item.id !== entry.id))}><Trash2 size={15} /></button></div></div><div className="form-grid">{config.fields.map(([key, label, multiline]) => <div key={key} className={multiline ? 'field-wide' : ''}><FormInput label={label} multiline={multiline} value={entry[key]} onChange={e => mutate(items => items.map(item => item.id === entry.id ? { ...item, [key]: e.target.value } : item))} /></div>)}</div></div>)}<button className="add-button" onClick={() => mutate(items => [...items, { id: crypto.randomUUID(), ...Object.fromEntries(config.fields.map(([key]) => [key, ''])) }])}><Plus size={17} />Tambah {config.label}</button></div>;
}
