import { useState } from 'react';
import { CheckCircle2, Circle, Target, ArrowUpRight, Lightbulb, Plus } from 'lucide-react';
import { careerProfiles, careerStages } from '../data/careerProfiles';
import { analyzeKeywords, reviewCV } from '../utils/career';
import { templates } from '../templates/registry';
import FormInput from './editor/FormInput';
export default function CareerCoach({ cvData, setCVData, onEdit }) {
  const target = cvData.jobTarget;
  const profile = careerProfiles.find(p => p.id === target.profile) || careerProfiles[0];
  const stage = careerStages.find(s => s.id === target.stage) || careerStages[2];
  const recommendation = templates.find(t => t.id === (stage.id === 'starter' ? 'graduate' : stage.id === 'switcher' ? 'career-switch' : profile.template));
  const checks = reviewCV(cvData);
  const keywords = analyzeKeywords(cvData);
  const [action, setAction] = useState('');
  const [context, setContext] = useState('');
  const [result, setResult] = useState('');
  const [saved, setSaved] = useState(false);
  const updateTarget = (key, value) => setCVData(prev => ({ ...prev, jobTarget: { ...prev.jobTarget, [key]: value } }));
  const bullet = [action.trim(), context.trim(), result.trim()].filter(Boolean).join(' — ');
  return <div className="career-panel">
    <div className="coach-intro"><span className="eyebrow">BUKAN HARUS SEMPURNA. HARUS RELEVAN.</span><h2>Siapkan CV untuk<br />peluang yang kamu tuju.</h2><p>Tidak ada CV yang menjamin diterima semua pekerjaan. Panel ini membantu kamu memperjelas bukti kemampuan dan menyesuaikan isi untuk setiap lowongan.</p><span className="local-label"><Target size={14} />Analisis teks lokal · tanpa unggahan</span></div>
    <section className="coach-card"><h3>01 · Tentukan arahmu</h3><div className="field"><label htmlFor="career-profile">Bidang tujuan</label><select id="career-profile" value={target.profile} onChange={e => updateTarget('profile', e.target.value)}>{careerProfiles.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></div><div className="field"><label htmlFor="career-stage">Tahap karier</label><select id="career-stage" value={target.stage} onChange={e => updateTarget('stage', e.target.value)}>{careerStages.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></div><div className="coach-advice"><Lightbulb size={18} /><div><strong>{profile.focus}</strong><p>{stage.advice}</p></div></div><ul className="coach-prompts">{profile.prompts.map(prompt => <li key={prompt}>{prompt}</li>)}</ul><button className="secondary-button" onClick={() => setCVData(prev => ({ ...prev, settings: { ...prev.settings, template: recommendation.id } }))}>{cvData.settings.template === recommendation.id ? 'Sedang digunakan:' : 'Gunakan struktur:'} {recommendation.name}<ArrowUpRight size={14} /></button><p className="microcopy">Saran berdasarkan struktur isi. Kamu tetap bebas memilih template lain.</p></section>
    <section className="coach-card"><div className="coach-title"><h3>02 · Periksa isi CV</h3><span>{checks.filter(c => c.pass).length}/{checks.length} cek dasar</span></div><p className="microcopy">Ini pemeriksaan kelengkapan sederhana, bukan skor ATS atau peluang diterima. Kebenaran isi, lisensi, dan syarat wajib tetap perlu kamu periksa sendiri.</p><ul className="review-list">{checks.map(check => <li key={check.id} className={check.pass ? 'passed' : ''}>{check.pass ? <CheckCircle2 size={17} /> : <Circle size={17} />}<div><strong>{check.label}</strong>{!check.pass && <p>{check.hint}</p>}</div></li>)}</ul><button className="secondary-button" onClick={onEdit}>Lengkapi di editor<ArrowUpRight size={14} /></button></section>
    <section className="coach-card"><h3>03 · Cocokkan dengan lowongan</h3><FormInput label="Deskripsi lowongan" multiline maxLength={30000} placeholder="Tempel tanggung jawab dan persyaratan lowongan di sini…" value={target.description} onChange={e => updateTarget('description', e.target.value)} /><FormInput label="Kata/frasa penting pilihanmu (pisahkan dengan koma)" maxLength={3000} placeholder="mis. Excel, pelayanan pelanggan, bahasa Inggris" value={target.keywords} onChange={e => updateTarget('keywords', e.target.value)} /><p className="microcopy">Saran otomatis memakai daftar istilah terbatas dari beberapa bidang. Tambahkan istilah yang terlewat. Pencocokan berupa kata/frasa, tanpa memahami konteks, sinonim, atau tingkat kemampuan.</p>
      {keywords.results.length ? <><div className="keyword-summary" role="status"><strong>{keywords.found} dari {keywords.results.length}</strong> kata/frasa tercantum di isi CV</div><div className="keyword-group"><h4>Sudah tercantum</h4><div className="keyword-chips">{keywords.results.filter(k => k.found).map(k => <span key={k.word} className="found"><CheckCircle2 size={12} />{k.word}</span>)}{keywords.found === 0 && <p>Belum ada yang cocok.</p>}</div></div><div className="keyword-group"><h4>Belum tercantum — tinjau relevansinya</h4><div className="keyword-chips">{keywords.results.filter(k => !k.found).map(k => <span key={k.word}>{k.word}</span>)}{keywords.found === keywords.results.length && <p>Semua istilah pilihan tercantum; periksa bukti dan konteksnya.</p>}</div></div><p className="microcopy">Tambahkan hanya kemampuan yang kamu miliki, dengan contoh bila relevan. Kemunculan istilah tidak membuktikan kamu memenuhi syarat. Deskripsi lowongan tidak ikut dicetak di CV.</p></> : <div className="coach-empty">{target.description ? 'Belum ada istilah dalam daftar yang terdeteksi. Tambahkan kata/frasa penting secara manual.' : 'Tempel lowongan atau masukkan kata kunci untuk mulai membandingkan.'}</div>}
    </section>
    <section className="coach-card"><h3>04 · Ceritakan kontribusi, bukan sekadar tugas</h3><p className="microcopy">Susun satu poin dari pengalaman nyata. Hasil boleh kualitatif; tidak perlu mengarang angka. Isian bantu ini tidak disimpan sampai kamu menambahkannya ke proyek.</p><FormInput label="Tindakan yang kamu lakukan" placeholder="mis. Mengatur jadwal relawan" value={action} onChange={e => { setAction(e.target.value); setSaved(false); }} /><FormInput label="Konteks / cara kamu mengerjakannya" placeholder="mis. dengan spreadsheet jadwal mingguan" value={context} onChange={e => { setContext(e.target.value); setSaved(false); }} /><FormInput label="Hasil yang bisa kamu pertanggungjawabkan" placeholder="mis. pembagian tugas menjadi lebih jelas" value={result} onChange={e => { setResult(e.target.value); setSaved(false); }} />{bullet && <blockquote className="bullet-preview">{bullet}</blockquote>}<button className="add-button" disabled={!action.trim() || saved} onClick={() => { setCVData(prev => ({ ...prev, projects: [...prev.projects, { id: crypto.randomUUID(), name: '', organization: '', date: '', link: '', description: bullet }] })); setSaved(true); }}><Plus size={16} />{saved ? 'Ditambahkan — lengkapi nama di editor' : 'Tambahkan sebagai draft proyek'}</button></section>
    <section className="coach-card coach-final"><h3>Sebelum mengirim</h3><ul><li>Baca syarat wajib dan format berkas yang diminta pemberi kerja.</li><li>Periksa kontak, ejaan, tautan, dan kebenaran setiap pernyataan.</li><li>Buka PDF hasil ekspor; cek pemenggalan halaman dan keterbacaan teks.</li><li>Simpan backup JSON tersendiri untuk setiap versi lamaran.</li></ul><p className="microcopy">Panduan penulisan: <a href="https://careerservices.fas.harvard.edu/resources/create-a-strong-resume/" target="_blank" rel="noreferrer">Harvard Career Services</a> dan <a href="https://ung.edu/career-services/online-career-resources/resumes-cover-letters/accomplishment-statements.php" target="_blank" rel="noreferrer">University of North Georgia</a>. Situs ini tidak menjalankan sistem seleksi perusahaan.</p></section>
  </div>;
}
